In [1]:
import numpy as np 

In [2]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [3]:
array1=np.array(list1)

In [4]:
array1

array([1, 2, 3, 4])

In [5]:
list2=[11,12,13,14]


In [6]:
mylist=[list1,list2]

In [7]:
mylist

[[1, 2, 3, 4], [11, 12, 13, 14]]

In [8]:
array2=np.array(mylist)

In [9]:
array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [10]:
array2.size

8

In [11]:
array2[0][2]

3

In [12]:
array2.shape

(2, 4)

In [13]:
array3=np.array((list1,list2))

In [14]:
array3

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [15]:
array3.shape

(2, 4)

In [16]:
array4=np.array(([1,2,'e',4],[11,12,13,14]))
array4.size

8

In [17]:

array4.shape

(2, 4)

In [18]:
array5=np.zeros(5)
array5

array([0., 0., 0., 0., 0.])

In [19]:
array6=np.ones((3,5))
array6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
array7=np.eye(3)
array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
array8=np.arange(5,100,5)
array8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [22]:
a='2'
b=a*4
b

'2222'

In [27]:
array7[:]=10

In [28]:
array7

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In list slicing provides you tne list with diffent memory set but in array you  will be having the shared location in sliced list so you have to use the copy function to create a different array

In [35]:
sliced_array=array8[:4]


In [36]:
sliced_array

array([ 5, 10, 15, 20])

In [37]:
sliced_array[0]=2

In [38]:
array8

array([ 2, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [39]:
array9=array8.copy()

In [40]:
array9[0]=5

In [41]:
array8

array([ 2, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [42]:
sliced_array[0]=5
array8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])