Scalar Array  operations

In [1]:
import numpy as np

In [17]:
aray1=np.array(([1,2,3,4],[5,6,7,8]))

In [18]:
aray1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
aray1[1][1]

6

In [21]:
aray1*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [22]:
aray1*aray1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [23]:
aray1-aray1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
aray1**3


array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [44]:
print(type(5.6))

<class 'float'>


In [38]:
print(4+''+'a')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [50]:
a='2'

In [51]:
a*3

'222'

In [60]:
l1=[1,2,3,4]
l1[0:5]

[1, 2, 3, 4]

In [57]:
aray2=np.arange(0,11)

In [58]:
aray2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
aray2[:4]

array([0, 1, 2, 3])

In [62]:
aray2[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
aray2[2:7]=aray2[2:7]*2

In [66]:
aray2

array([ 0,  1,  4,  6,  8, 10, 12,  7,  8,  9, 10])

In [67]:
aray2[2:7]=aray2[2:7]/2

In [68]:
aray2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
aray=aray2[2:7]

In [77]:
aray[:]=100

In [78]:
aray

array([100, 100, 100, 100, 100])

In [79]:
aray2

array([  0,   1, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [81]:
aray[:]=aray2[2:7]/2
aray

array([50, 50, 50, 50, 50])