In [2]:
import numpy as np 

In [7]:
list1=[1,2,3,4]

list1

[1, 2, 3, 4]

In [8]:
array1=np.array(list1)

In [9]:
print(array1)

[1 2 3 4]


In [10]:
list2=[11,12,13,14]


In [11]:
mylist=[list1,list2]

In [12]:
mylist

[[1, 2, 3, 4], [11, 12, 13, 14]]

In [13]:
array2=np.array(mylist)

In [14]:
array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [15]:
array2.size

8

In [16]:
array2[0][2]

3

In [17]:
array2.shape

(2, 4)

In [18]:
array3=np.array((list1,list2))

In [19]:
array3

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [20]:
array3.shape

(2, 4)

In [21]:
array4=np.array(([1,2,'e',4],[11,12,13,14]))
array4.size

8

In [22]:

array4.shape

(2, 4)

In [57]:
array5=np.zeros((5,4))
array5.shape


(5, 4)

In [58]:
array5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
array6=np.ones((3,5))
array6.dtype

dtype('float64')

In [25]:
array7=np.eye(3)
array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
array8=np.arange(5,100,5)
array8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [27]:
a='2'
b=a*4
b

'2222'

In [60]:
array7[:]=10

In [61]:
array7

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In list slicing provides you a list with different memory refrence but in array you  will be having the shared location in sliced array so you have to use the copy function to create a different array

In [37]:
sliced_array=array8[:4]


In [38]:
sliced_array

array([ 5, 10, 15, 20])

In [39]:
sliced_array[0]=2

In [40]:
array8

array([ 2, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [41]:
array9=array8.copy()

In [42]:
array9[0]=5

In [43]:
array8

array([ 2, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [46]:
sliced_array[0]=5
array8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [45]:
print(10/5)

2.0


In [39]:
print(type(5))

<class 'int'>


In [40]:
print('a'+' '+'b') #this is concatenation but unlike java you can not concatenate the integer aliteral with a character 

a b


In [47]:
print('a'+' '+4) #this will throw the error 

TypeError: must be str, not int

In [42]:
l=[12,34] 
k=[a,l]
k

[[1, 'b', 'c'], [12, 34]]

In [20]:
artTest=np.array(((1,23,45,56),np.arange(4,11,2),np.arange(55,71,5),np.arange(49,12,-12)))