In [1]:
import os 


In [4]:
os.chdir('/media/abhishek/New Volume/Python')


In [5]:
os.getcwd()

'/media/abhishek/New Volume/Python'

In [7]:
import numpy as np
import pandas as pd 


In [83]:
np.arange(12) # here it will generate the first 12 number  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
sample_matrix=np.matrix([[1,43,411],[1 ,4 ,6]]) # way 1 more preferable

In [71]:
sample_matrix

numpy.matrixlib.defmatrix.matrix

In [25]:
sample_matrix=np.matrix('1,2,3;4,5,6') #second way to create the matrix

In [26]:
sample_matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [28]:
np.transpose(sample_matrix)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [29]:
#Scalar operation with the matrix


In [30]:
sample_matrix/2**3

matrix([[0.125, 0.25 , 0.375],
        [0.5  , 0.625, 0.75 ]])

In [31]:
#how to create a data frame 


In [40]:
sample_dataframe=pd.DataFrame({'Gender':['M','F','M'],'Income':[4000,5000,5000]})

In [84]:
sample_dataframe

pandas.core.frame.DataFrame

In [48]:
#to rename the dataframe

In [ ]:
sample_dataframe1=sample_dataframe.rename(columns={'Gender':'Gender_v','Income':'Income_v'})

In [49]:
sample_dataframe1


Gender_v  Income_v
0        M      4000
1        F      5000
2        M      5000

In [50]:
#you can also import the datasets from R library

In [53]:
data_frame=pd.read_csv('Mtcars.csv')

In [54]:
data_frame

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [56]:
data_frame.shape

(32, 12)

In [57]:
#to subset the specific columns

In [58]:
data_frame_subset=data_frame[['mpg','carb']]

In [59]:
data_frame_subset

mpg  carb
0   21.0     4
1   21.0     4
2   22.8     1
3   21.4     1
4   18.7     2
5   18.1     1
6   14.3     4
7   24.4     2
8   22.8     2
9   19.2     4
10  17.8     4
11  16.4     3
12  17.3     3
13  15.2     3
14  10.4     4
15  10.4     4
16  14.7     4
17  32.4     1
18  30.4     2
19  33.9     1
20  21.5     1
21  15.5     2
22  15.2     2
23  13.3     4
24  19.2     2
25  27.3     1
26  26.0     2
27  30.4     2
28  15.8     4
29  19.7     6
30  15.0     8
31  21.4     2

In [60]:
# to select the specific columns from the dataframe based on condtion

In [69]:
data_frame_condition=data_frame.ix[(data_frame['cyl']==6)&(data_frame['carb']==4)]

In [70]:
data_frame_condition

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0       Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1   Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
9        Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
10      Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   

    carb  
0      4  
1      4  
9      4  
10     4

In [80]:
#How to define the new variable from the existing one 

In [87]:
data_frame['new_var']=np.log2(data_frame['cyl'])*2

In [88]:
data_frame

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb   new_var  
0      4     4  5.169925  
1      4     4  5.169925  
2      4     1  4.000000  
3      3     1  5.169925  
4      3     2  6.000000  
5      3     1  5.169925  
6      3     4  6.000000  
7      4     2  4.000000  
8      4     2  4.000000  
9      4     4  5.169925  
10     4     4  5.169925  
11     3     3  6.000000  
12     3     3  6.000000  
13     3     3  6.000000  
14     3     4  6.000000  
15     3     4  6.000000  
16     3     4  6.000000  
17     4     1  4.000000  
18     4     2  4.000000  
19     4     1  4.000000  
20     3     1  4.000000  
21     3     2  6.000000  
22     3     2  6.000000  
23     3     4  6.000000  
24     3     2  6.000000  
25     4     1  4.000000  
26     5     2  4.000000  
27     5     2  4.000000  
28     5     4  6.000000  
29     5     6  5.169925  
30     5     8  6.000000  
31     4     2  4.000000

In [89]:
#How to appned the two data frames(rowbind)(union)

In [105]:
d1=pd.DataFrame({'a':[5,4,3,2],'b':[4,3,2,1]})

In [106]:
d2=pd.DataFrame({'a':[5,4,3,2],'b':[6,5,4,3]})

In [112]:
d3=d1.append([d2])

In [113]:
 d3

a  b
0  5  4
1  4  3
2  3  2
3  2  1
0  5  6
1  4  5
2  3  4
3  2  3

In [98]:
d4=d1.concat(d2)

AttributeError: 'DataFrame' object has no attribute 'concat'